name: "Deploy feature branch or main kubernetes manifests"
description: "Deploys kubernetes manifests for feature branches or main branch. Replaces image tag in deployment and uploads the manifests bundle as an artifact. "

inputs:
  manifest-path:
    description: "Path to the kubernetes manifest file to be deployed"
    required: true
  docker-image:
    description: "Image tag to be replaced in deployment"
    required: true
  feature-branch-prefix:
    description: "Prefix for feature branch deployment (minimum 6 characters)"
    required: false

runs:
  using: "composite"
  steps:
    - name: Check if PR is still open for feature branch deployment
      if: github.event_name == 'pull_request' && inputs.feature-branch-prefix
      uses: actions/github-script@v6
      with:
        script: |
          const { data: pr } = await github.rest.pulls.get({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.issue.number,
          });
          if (pr.state !== 'open') {
            core.setFailed("Cannot deploy feature branch when PR is closed. Exiting with status code 1.");
            process.exit(1);
          }

    - name: Replacing the environment variables in manifest file
      shell: bash
      env:
        FEATURE_BRANCH_PREFIX: ${{ inputs.feature-branch-prefix }}
        DOCKER_IMAGE: ${{ inputs.docker-image }}
      run: |
        envsubst < "${{ inputs.manifest-path }}" > "${{ inputs.manifest-path }}.tmp" && mv "${{ inputs.manifest-path }}.tmp" "${{ inputs.manifest-path }}"        

    - name: Upload Manifests Bundle Artifact
      uses: actions/upload-artifact@v4
      with:
        name: manifests-bundle
        path: ${{ inputs.manifest-path }}

# Here you need to add steps for deploying the manifest in your cluster.
